/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPlayBankIdRouteImport } from './routes/_authenticated/play.$bankId'
import { Route as AuthenticatedGuruRoomsRouteImport } from './routes/_authenticated/guru.rooms'
import { Route as AuthenticatedCreatorBanksIndexRouteImport } from './routes/_authenticated/creator.banks.index'
import { Route as AuthenticatedCreatorBanksBankIdRouteImport } from './routes/_authenticated/creator.banks.$bankId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayBankIdRoute = AuthenticatedPlayBankIdRouteImport.update({
  id: '/play/$bankId',
  path: '/play/$bankId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuruRoomsRoute = AuthenticatedGuruRoomsRouteImport.update({
  id: '/guru/rooms',
  path: '/guru/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorBanksIndexRoute =
  AuthenticatedCreatorBanksIndexRouteImport.update({
    id: '/creator/banks/',
    path: '/creator/banks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorBanksBankIdRoute =
  AuthenticatedCreatorBanksBankIdRouteImport.update({
    id: '/creator/banks/$bankId',
    path: '/creator/banks/$bankId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guru/rooms': typeof AuthenticatedGuruRoomsRoute
  '/play/$bankId': typeof AuthenticatedPlayBankIdRoute
  '/creator/banks/$bankId': typeof AuthenticatedCreatorBanksBankIdRoute
  '/creator/banks/': typeof AuthenticatedCreatorBanksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guru/rooms': typeof AuthenticatedGuruRoomsRoute
  '/play/$bankId': typeof AuthenticatedPlayBankIdRoute
  '/creator/banks/$bankId': typeof AuthenticatedCreatorBanksBankIdRoute
  '/creator/banks': typeof AuthenticatedCreatorBanksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guru/rooms': typeof AuthenticatedGuruRoomsRoute
  '/_authenticated/play/$bankId': typeof AuthenticatedPlayBankIdRoute
  '/_authenticated/creator/banks/$bankId': typeof AuthenticatedCreatorBanksBankIdRoute
  '/_authenticated/creator/banks/': typeof AuthenticatedCreatorBanksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/guru/rooms'
    | '/play/$bankId'
    | '/creator/banks/$bankId'
    | '/creator/banks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/guru/rooms'
    | '/play/$bankId'
    | '/creator/banks/$bankId'
    | '/creator/banks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/guru/rooms'
    | '/_authenticated/play/$bankId'
    | '/_authenticated/creator/banks/$bankId'
    | '/_authenticated/creator/banks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$bankId': {
      id: '/_authenticated/play/$bankId'
      path: '/play/$bankId'
      fullPath: '/play/$bankId'
      preLoaderRoute: typeof AuthenticatedPlayBankIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/rooms': {
      id: '/_authenticated/guru/rooms'
      path: '/guru/rooms'
      fullPath: '/guru/rooms'
      preLoaderRoute: typeof AuthenticatedGuruRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/banks/': {
      id: '/_authenticated/creator/banks/'
      path: '/creator/banks'
      fullPath: '/creator/banks/'
      preLoaderRoute: typeof AuthenticatedCreatorBanksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/banks/$bankId': {
      id: '/_authenticated/creator/banks/$bankId'
      path: '/creator/banks/$bankId'
      fullPath: '/creator/banks/$bankId'
      preLoaderRoute: typeof AuthenticatedCreatorBanksBankIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuruRoomsRoute: typeof AuthenticatedGuruRoomsRoute
  AuthenticatedPlayBankIdRoute: typeof AuthenticatedPlayBankIdRoute
  AuthenticatedCreatorBanksBankIdRoute: typeof AuthenticatedCreatorBanksBankIdRoute
  AuthenticatedCreatorBanksIndexRoute: typeof AuthenticatedCreatorBanksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuruRoomsRoute: AuthenticatedGuruRoomsRoute,
  AuthenticatedPlayBankIdRoute: AuthenticatedPlayBankIdRoute,
  AuthenticatedCreatorBanksBankIdRoute: AuthenticatedCreatorBanksBankIdRoute,
  AuthenticatedCreatorBanksIndexRoute: AuthenticatedCreatorBanksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
