/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGuruRoomsRouteImport } from './routes/_authenticated/guru.rooms'
import { Route as AuthenticatedCreatorBanksRouteImport } from './routes/_authenticated/creator.banks'
import { Route as AuthenticatedCreatorBanksBankIdRouteImport } from './routes/_authenticated/creator.banks.$bankId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuruRoomsRoute = AuthenticatedGuruRoomsRouteImport.update({
  id: '/guru/rooms',
  path: '/guru/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorBanksRoute =
  AuthenticatedCreatorBanksRouteImport.update({
    id: '/creator/banks',
    path: '/creator/banks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorBanksBankIdRoute =
  AuthenticatedCreatorBanksBankIdRouteImport.update({
    id: '/$bankId',
    path: '/$bankId',
    getParentRoute: () => AuthenticatedCreatorBanksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/creator/banks': typeof AuthenticatedCreatorBanksRouteWithChildren
  '/guru/rooms': typeof AuthenticatedGuruRoomsRoute
  '/creator/banks/$bankId': typeof AuthenticatedCreatorBanksBankIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/creator/banks': typeof AuthenticatedCreatorBanksRouteWithChildren
  '/guru/rooms': typeof AuthenticatedGuruRoomsRoute
  '/creator/banks/$bankId': typeof AuthenticatedCreatorBanksBankIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/creator/banks': typeof AuthenticatedCreatorBanksRouteWithChildren
  '/_authenticated/guru/rooms': typeof AuthenticatedGuruRoomsRoute
  '/_authenticated/creator/banks/$bankId': typeof AuthenticatedCreatorBanksBankIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/creator/banks'
    | '/guru/rooms'
    | '/creator/banks/$bankId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/creator/banks'
    | '/guru/rooms'
    | '/creator/banks/$bankId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/creator/banks'
    | '/_authenticated/guru/rooms'
    | '/_authenticated/creator/banks/$bankId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/rooms': {
      id: '/_authenticated/guru/rooms'
      path: '/guru/rooms'
      fullPath: '/guru/rooms'
      preLoaderRoute: typeof AuthenticatedGuruRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/banks': {
      id: '/_authenticated/creator/banks'
      path: '/creator/banks'
      fullPath: '/creator/banks'
      preLoaderRoute: typeof AuthenticatedCreatorBanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/banks/$bankId': {
      id: '/_authenticated/creator/banks/$bankId'
      path: '/$bankId'
      fullPath: '/creator/banks/$bankId'
      preLoaderRoute: typeof AuthenticatedCreatorBanksBankIdRouteImport
      parentRoute: typeof AuthenticatedCreatorBanksRoute
    }
  }
}

interface AuthenticatedCreatorBanksRouteChildren {
  AuthenticatedCreatorBanksBankIdRoute: typeof AuthenticatedCreatorBanksBankIdRoute
}

const AuthenticatedCreatorBanksRouteChildren: AuthenticatedCreatorBanksRouteChildren =
  {
    AuthenticatedCreatorBanksBankIdRoute: AuthenticatedCreatorBanksBankIdRoute,
  }

const AuthenticatedCreatorBanksRouteWithChildren =
  AuthenticatedCreatorBanksRoute._addFileChildren(
    AuthenticatedCreatorBanksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCreatorBanksRoute: typeof AuthenticatedCreatorBanksRouteWithChildren
  AuthenticatedGuruRoomsRoute: typeof AuthenticatedGuruRoomsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCreatorBanksRoute: AuthenticatedCreatorBanksRouteWithChildren,
  AuthenticatedGuruRoomsRoute: AuthenticatedGuruRoomsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
